apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: imageswap-webhook
  labels:
    app: imageswap
    resource: mutatingwebhookconfiguration
webhooks:
  - name: imageswap.webhook.k8s.twr.io
    clientConfig:
      service:
        name: imageswap
        namespace: imageswap-system
        path: "/"
      caBundle: $CA_BUNDLE
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - "pods"
    sideEffects: None
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    reinvocationPolicy: IfNeeded
    namespaceSelector:
      matchLabels:
        k8s.twr.io/imageswap: "enabled"
